-- Instituto Mara — tanda 5 del catálogo (1 diplomado y 5 cursos).
-- Ejecutar en Supabase → SQL Editor. Se puede repetir: actualiza si ya existen.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-seguridad-higiene', 'Diplomado en Seguridad e Higiene en el Trabajo (Normas STPS)', 'Aprende a identificar peligros, evaluar riesgos y organizar la seguridad de tu centro de trabajo con las principales normas de la STPS: comisión de seguridad e higiene, equipo de protección personal, incendios, señalización, químicos, ergonomía, ruido, emergencias e investigación de accidentes. Con matrices e indicadores en hoja de cálculo. Para supervisores, RH, EHS, comisiones y dueños de pymes y talleres. No sustituye la asesoría de un especialista.', '#EA580C', 'Diplomados', 'Recursos Humanos y empresa', null, null, 32, 1890, true, false),
  ('c-ingles-b1', 'Inglés B1 (intermedio)', 'La continuación del Inglés A2: cuenta anécdotas con naturalidad, habla de lo que llevas haciendo, negocia planes con condicionales, opina y difiere con cortesía en juntas, escribe correos formales, resuelve problemas de viaje y prepárate para una entrevista de trabajo en inglés. Con voz para escuchar cada frase y ejercicios para practicar tu pronunciación.', '#4338CA', 'Cursos libres de capacitación', 'Idiomas', null, null, 24, 990, true, false),
  ('c-venta-en-linea', 'Vende en Línea: WhatsApp Business, Mercado Libre y Redes', 'Aprende a vender desde tu celular por WhatsApp Business, Mercado Libre, Facebook Marketplace, Instagram y TikTok. Calcula precios que sí dejan ganancia, toma fotos que venden, cobra de forma segura, evita fraudes y organiza pedidos, envíos y tus obligaciones fiscales básicas. Para emprendedores, comerciantes, artesanos y quien vende por catálogo o desde casa.', '#16A34A', 'Cursos libres de capacitación', 'Negocios y finanzas', null, null, 14, 890, true, false),
  ('c-canva', 'Diseño con Canva y Marca Personal', 'Aprende los principios básicos del diseño sin ser diseñador y úsalos en Canva para crear publicaciones, historias, flyers, menús, presentaciones y tarjetas que se vean profesionales. Después construye tu marca personal: bio, CV que pase los filtros de reclutamiento, perfil de LinkedIn, portafolio sencillo y un plan de contenido de 30 días. Ideal para emprendedores, independientes y personal de marketing o de oficina.', '#7C3AED', 'Cursos libres de capacitación', 'Tecnología', null, null, 12, 790, true, false),
  ('c-productividad', 'Productividad y Gestión del Tiempo', 'Descubre a dónde se va tu tiempo, prioriza con métodos probados como la matriz de Eisenhower, los bloques de tiempo y la técnica Pomodoro, domina el correo y el WhatsApp de trabajo sin vivir en ellos, y arma tu plan personal de 30 días con seguimiento en hoja de cálculo. Para quienes trabajan, estudian o sacan adelante la doble jornada.', '#0891B2', 'Cursos libres de capacitación', 'Desarrollo humano', null, null, 10, 690, true, false),
  ('c-logistica', 'Logística, Almacén e Inventarios', 'Aprende a recibir, acomodar, contar y surtir mercancía sin perder dinero: kardex, conteo cíclico, clasificación ABC, punto de reorden, lote económico, rotación, costos de envío y un tablero de indicadores con OTIF y exactitud de inventario, todo practicado en hoja de cálculo. Para auxiliares de almacén, supervisores de logística, compradores y dueños de tiendas, ferreterías, refaccionarias y negocios de e-commerce.', '#B45309', 'Cursos libres de capacitación', 'Administración y oficina', null, null, 16, 990, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
