-- Instituto Mara — tanda 2 del catálogo (3 diplomados y 3 cursos).
-- Ejecutar en Supabase → SQL Editor. Se puede repetir: actualiza si ya existen.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-tanatologia', 'Diplomado en Tanatología y Acompañamiento en el Duelo', 'Aprende a acompañar con respeto a personas que enfrentan la muerte y el duelo: qué decir y qué no, cómo apoyar a familias y a niños, cuándo canalizar y cómo cuidarte tú. Diplomado libre con constancia de Instituto Mara; no habilita para dar psicoterapia.', '#7C3AED', 'Diplomados', 'Salud y bienestar', null, null, 40, 1990, true, false),
  ('d-nom035', 'Diplomado NOM-035: Factores de Riesgo Psicosocial en el Trabajo', 'Aprende a cumplir la NOM-035-STPS-2018 paso a paso: obligaciones según el tamaño del centro de trabajo, Guías de referencia I, II y III, calificación de cuestionarios en Excel, plan de acción y registros. Incluye formatos listos para usar; no sustituye la lectura de la norma publicada en el DOF ni la asesoría legal o clínica.', '#0F766E', 'Diplomados', 'Recursos Humanos y empresa', null, null, 30, 1790, true, false),
  ('c-pap', 'Primeros Auxilios Psicológicos', 'Aprende a dar apoyo humano inmediato a una persona en crisis (escuchar, calmar, cubrir necesidades y canalizar) y a reconocer cuándo derivar a profesionales. No es terapia ni habilita para darla.', '#DB2777', 'Cursos libres de capacitación', 'Salud y bienestar', null, null, 10, 690, true, false),
  ('c-excel-avanzado', 'Excel Intermedio y Avanzado', 'Da el salto de las sumas a las fórmulas que piden en la oficina: referencias con $, SI anidados, BUSCARV, BUSCARX, INDICE y COINCIDIR, SUMAR.SI.CONJUNTO, limpieza de textos, tablas dinámicas y un tablero de ventas. Con hojas de práctica donde escribes fórmulas de verdad.', '#15803D', 'Cursos libres de capacitación', 'Tecnología', null, null, 14, 990, true, false),
  ('c-ingles-a2', 'Inglés A2 (pre-intermedio)', 'La continuación del Inglés A1: aprende a contar lo que hiciste, hablar de tus planes, comparar opciones, dar consejos y usar el inglés en tu trabajo con correos, llamadas y reuniones. Con voz para escuchar cada frase y ejercicios para practicar tu pronunciación.', '#4F46E5', 'Cursos libres de capacitación', 'Idiomas', null, null, 20, 890, true, false),
  ('d-adulto-mayor', 'Diplomado en Cuidado del Adulto Mayor', 'Aprende a cuidar a una persona mayor con dignidad y seguridad: higiene, movilidad, prevención de caídas, alimentación, organización de medicamentos y señales de alarma. Pensado para familiares y personas que quieren trabajar como cuidadoras; no sustituye la atención médica ni de enfermería.', '#B45309', 'Diplomados', 'Salud y bienestar', null, null, 30, 1690, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
