-- Instituto Mara — tanda 7 del catálogo (2 diplomados y 2 cursos).
-- Ejecutar en Supabase → SQL Editor ANTES de rutas.sql. Se puede repetir.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-terapias-contextuales', 'Diplomado en Terapias Contextuales: ACT, DBT y Activación Conductual', 'Da el paso de la TCC clásica al enfoque contextual: análisis funcional, formulación con la matriz ACT, los seis procesos de la terapia de aceptación y compromiso, las habilidades de la DBT, la activación conductual, la psicoterapia analítica funcional y el mindfulness con evidencia, con casos ficticios y hojas de cálculo para medir el avance. Es para psicólogos con cédula, estudiantes avanzados de psicología y psicoterapeutas cognitivo-conductuales. Da fundamentos y técnicas; no sustituye la formación clínica supervisada ni las certificaciones de cada modelo, y no habilita para ejercer la psicoterapia.', '#0D9488', 'Diplomados', 'Salud y bienestar', null, null, 40, 2490, true, false),
  ('d-evaluacion-clinica', 'Diplomado en Evaluación Psicológica y Formulación de Casos Clínicos', 'Para psicólogos con cédula y estudiantes de los últimos semestres que no saben por dónde empezar cuando llega un paciente. Aprende a conducir la primera consulta, evaluar el estado mental y el riesgo, usar la CIE-11 y el DSM-5-TR con criterio, formular el caso con el modelo de las 5 P, medir resultados sesión a sesión y documentar bien tu expediente. Casos ficticios y práctica constante; no sustituye la supervisión clínica.', '#7C3AED', 'Diplomados', 'Salud y bienestar', null, null, 30, 1790, true, false),
  ('c-ia-psicologos', 'IA para Psicólogos y Consultorios de Salud Mental', 'Para psicólogos, psicoterapeutas, tanatólogos, orientadores y consultorios pequeños: usa asistentes de IA para notas, informes, agenda, materiales de psicoeducación y actualización profesional, quitándole horas al papeleo sin poner en riesgo la confidencialidad ni la calidad clínica. La IA no diagnostica ni sustituye tu juicio clínico.', '#8B5CF6', 'Cursos libres de capacitación', 'IA por profesión', null, null, 10, 790, true, false),
  ('c-fotografia-producto', 'Fotografía de Producto con el Celular', 'Aprende a tomar fotos que venden con tu celular y materiales baratos de casa o de la papelería: luz de ventana, difusor y rebotador caseros, fondo infinito, reflejos en perfumes y joyería, composición, fotos para Mercado Libre, el catálogo de WhatsApp, Instagram y Facebook, edición básica y una sesión de 20 fotos en una hora. Es para emprendedores, artesanos y vendedores de perfumes, joyería, ropa, postres, cosméticos o refacciones. No necesitas cámara profesional ni experiencia.', '#E11D48', 'Cursos libres de capacitación', 'Negocios y finanzas', null, null, 10, 690, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;

-- Precios de rutas que cambiaron (rutas.sql no sobrescribe precios existentes)
update cursos set precio = 1990 where id = 'r-ingles';
update cursos set precio = 2690 where id = 'r-vende';
