-- Instituto Mara — tanda 3 del catálogo (3 diplomados y 3 cursos).
-- Ejecutar en Supabase → SQL Editor. Se puede repetir: actualiza si ya existen.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('c-inteligencia-emocional', 'Inteligencia emocional y manejo del estrés', 'Aprende a reconocer lo que sientes, calmarte antes de reaccionar, manejar el estrés del día a día y comunicarte mejor en el trabajo y en casa, con herramientas prácticas y basadas en evidencia. No es terapia: te enseña también cuándo y dónde buscar ayuda profesional.', '#7C3AED', 'Cursos libres de capacitación', 'Desarrollo humano', null, null, 12, 790, true, false),
  ('c-finanzas-personales', 'Finanzas personales y salir de deudas', 'Aprende a saber en qué se va tu dinero, armar un presupuesto quincenal que sí se cumpla, entender el costo real de tus deudas y salir de ellas con un plan, y proteger tu dinero de fraudes. Es un curso educativo con ejercicios en hoja de cálculo; no es asesoría financiera personalizada.', '#15803D', 'Cursos libres de capacitación', 'Negocios y finanzas', null, null, 16, 890, true, false),
  ('d-marketing-digital', 'Diplomado en Marketing Digital y Redes Sociales para Negocios', 'Arma la estrategia digital de tu negocio paso a paso: cliente ideal, WhatsApp Business y perfil de Google, contenido para redes, anuncios pagados y medición en hoja de cálculo. Es práctico y con ejemplos mexicanos; no promete ventas garantizadas: te enseña a probar, medir y decidir con datos.', '#EA580C', 'Diplomados', 'Negocios y finanzas', null, null, 32, 1690, true, false),
  ('d-contabilidad-resico', 'Diplomado en Contabilidad Básica, RESICO y Facturación CFDI 4.0', 'Aprende a llevar las cuentas de tu negocio, leer tus números en hoja de cálculo, calcular tu ISR en el RESICO y tu IVA, y facturar bien en CFDI 4.0. Es práctico y para personas físicas con negocios pequeños; no sustituye la asesoría de un contador público.', '#1D4ED8', 'Diplomados', 'Negocios y finanzas', null, null, 32, 1890, true, false),
  ('c-atencion-ventas', 'Atención al cliente y ventas', 'Aprende a atender en mostrador, por teléfono y por WhatsApp, a resolver quejas con calma, a vender preguntando en lugar de presionar y a medir tus resultados con indicadores sencillos. Incluye guiones y plantillas listas para usar en tu trabajo.', '#0891B2', 'Cursos libres de capacitación', 'Negocios y finanzas', null, null, 12, 790, true, false),
  ('d-liderazgo', 'Diplomado en Liderazgo para Mandos Medios', 'Para supervisores, jefes de turno y coordinadores que acaban de subir de puesto: cómo dar instrucciones claras, retroalimentar, delegar, medir a tu equipo en Excel, manejar conflictos y cumplir tu papel en la NOM-035. Práctico y con formatos listos; al terminar recibes una constancia de Instituto Mara.', '#B45309', 'Diplomados', 'Recursos Humanos y empresa', null, null, 30, 1690, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
