-- Instituto Mara — tanda 4 del catálogo (3 diplomados y 3 cursos).
-- Ejecutar en Supabase → SQL Editor. Se puede repetir: actualiza si ya existen.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-proyectos', 'Diplomado en Gestión de Proyectos y Metodologías Ágiles', 'Para quienes «les tocó» un proyecto sin formación formal: abrir una sucursal, organizar un evento, lanzar una app o implementar un sistema. Aprende a definir alcance, armar cronograma y ruta crítica, presupuestar, manejar riesgos, trabajar con Scrum y Kanban, medir avance con valor ganado en hoja de cálculo y cerrar bien. Te da bases para certificaciones como PMP o Scrum Master, que otorgan organismos externos y no este diplomado.', '#0369A1', 'Diplomados', 'Administración y oficina', null, null, 32, 1790, true, false),
  ('d-recursos-humanos', 'Diplomado en Recursos Humanos: Reclutamiento, Nómina y Ley Federal del Trabajo', 'Aprende a contratar bien, calcular aguinaldo, vacaciones, horas extra y finiquitos en hoja de cálculo, cumplir con lo básico de la Ley Federal del Trabajo y desarrollar a tu equipo con indicadores claros. Pensado para auxiliares y generalistas de RH, dueños de pymes y administradores que llevan el personal; no sustituye la asesoría de un abogado laboral ni de un contador.', '#9333EA', 'Diplomados', 'Recursos Humanos y empresa', null, null, 36, 1990, true, false),
  ('c-power-bi', 'Análisis de Datos con Excel y Power BI', 'Convierte tus tablas de Excel en reportes y tableros que responden preguntas de negocio. Aprende a limpiar datos, resumir con SUMAR.SI.CONJUNTO, calcular variaciones, participaciones y rankings, armar tablas dinámicas y gráficos que sí se entienden, y dar tus primeros pasos en Power BI Desktop con Power Query, modelo de datos y medidas DAX. Es la continuación natural de Excel Intermedio y Avanzado.', '#CA8A04', 'Cursos libres de capacitación', 'Tecnología', null, null, 16, 990, true, false),
  ('d-asistente-administrativo', 'Diplomado de Asistente Administrativo y Recepción', 'Prepárate para conseguir tu primer empleo de oficina o recepción, o para subir de puesto. Aprende a atender en persona y por teléfono, tomar recados completos, llevar agendas, redactar correos, minutas y oficios, archivar sin perder nada, manejar caja chica, viáticos e inventario en hoja de cálculo, revisar que una factura traiga bien los datos y usar herramientas de oficina e IA con responsabilidad. Incluye plantillas de CV, carta de presentación y documentos listos para usar.', '#0D9488', 'Diplomados', 'Administración y oficina', null, null, 30, 1490, true, false),
  ('c-comunicacion', 'Comunicación Efectiva, Oratoria y Redacción Profesional', 'Aprende a expresarte con claridad y seguridad en juntas, presentaciones, correos, mensajes de WhatsApp de trabajo y entrevistas. Practica escucha activa, comunicación asertiva, manejo de nervios, la ortografía que más se equivoca en México y conversaciones difíciles como pedir un aumento o dar retroalimentación. Incluye plantillas listas para usar.', '#DB2777', 'Cursos libres de capacitación', 'Desarrollo humano', null, null, 14, 890, true, false),
  ('c-ciberseguridad', 'Ciberseguridad Personal y Prevención de Fraudes', 'Aprende a reconocer las estafas más comunes en México (llamadas del «banco», SMS y correos falsos, WhatsApp robado, falso familiar, ventas y préstamos fraudulentos), a blindar tus cuentas y tu banca móvil, y a saber exactamente qué hacer y a dónde acudir si ya te pasó. Práctico, con casos reales y 100% defensivo; incluye un plan de seguridad para tu familia.', '#DC2626', 'Cursos libres de capacitación', 'Tecnología', null, null, 10, 690, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
