-- Instituto Mara — tanda 6 del catálogo (3 diplomados y 3 cursos).
-- Ejecutar en Supabase → SQL Editor ANTES de rutas.sql. Se puede repetir.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-tcc', 'Diplomado en Terapia Cognitivo-Conductual: Fundamentos y Técnicas', 'Aprende el modelo cognitivo-conductual y sus técnicas con base en la evidencia: formulación de casos, registro de pensamientos, cuestionamiento socrático, activación conductual, exposición gradual, estructura de sesión, prevención de recaídas y ética profesional, con casos ficticios y hojas de cálculo para dar seguimiento. Es para estudiantes y profesionales de psicología y para quienes trabajan en salud, educación o recursos humanos. Da fundamentos y técnicas; no habilita para ejercer la psicoterapia, que en México requiere formación profesional en psicología y cédula.', '#9333EA', 'Diplomados', 'Salud y bienestar', null, null, 40, 2490, true, false),
  ('d-neurodiversidad', 'Diplomado en Educación Inclusiva y Neurodiversidad (TEA, TDAH y Dificultades de Aprendizaje)', 'Para docentes de preescolar a secundaria, maestras sombra, orientadores, madres, padres y cuidadores. Aprende a reconocer señales de autismo (TEA), TDAH y dificultades específicas del aprendizaje, a adaptar el aula y la casa con apoyos basados en evidencia y a trabajar en equipo con la familia y los especialistas. No capacita para diagnosticar: el diagnóstico lo hace un profesional de la salud.', '#0EA5E9', 'Diplomados', 'Salud y bienestar', null, null, 32, 1990, true, false),
  ('d-infancia-adolescencia', 'Diplomado en Salud Emocional de Niños y Adolescentes: Detección y Acompañamiento', 'Para docentes, orientadores, madres, padres y personal que trabaja con niñas, niños y adolescentes. Aprende cómo se desarrollan las emociones, a reconocer señales de alerta (ansiedad, tristeza persistente, acoso, riesgos en línea), a escuchar y poner límites sin violencia, y a canalizar a tiempo con un plan y un directorio. No capacita para diagnosticar ni dar tratamiento: te prepara para detectar, acompañar y pedir la ayuda correcta.', '#F59E0B', 'Diplomados', 'Salud y bienestar', null, null, 32, 1990, true, false),
  ('c-ansiedad-depresion', 'Ansiedad y Depresión: Entender, Detectar y Acompañar', 'Entiende qué son la ansiedad y la depresión con información basada en evidencia (OMS, CIE-11, DSM-5-TR y guías NICE): la diferencia entre una emoción normal y un trastorno, las señales de alerta, qué hacer ante un ataque de pánico, herramientas de autocuidado con respaldo como la respiración lenta y la activación conductual, cómo acompañar a alguien sin juzgar, cómo preguntar por ideas de suicidio y a dónde canalizar en México. Es para público general, familiares, personal de recursos humanos, docentes y líderes de equipo. No diagnostica ni trata, ni sustituye la atención de psicología o psiquiatría.', '#6366F1', 'Cursos libres de capacitación', 'Salud y bienestar', null, null, 14, 890, true, false),
  ('c-neurociencia', 'Neurociencia Aplicada: Aprendizaje, Emociones y Hábitos', 'Entiende qué dice de verdad la neurociencia sobre cómo aprendemos, sentimos y formamos hábitos, y aprende a separar la evidencia de los neuromitos y del «neuromarketing» exagerado. Verás neuronas, memoria, práctica espaciada y de recuperación, estrés y emociones, sesgos cognitivos, dopamina sin mitos, hábitos, pantallas, ejercicio, sueño y mindfulness con sus alcances reales, con hojas de cálculo para armar tu calendario de repaso y tu plan de 30 días. Es para docentes, capacitadores, líderes, estudiantes y público curioso. Es un curso de divulgación: no forma neurocientíficos ni profesionales clínicos.', '#DB2777', 'Cursos libres de capacitación', 'Desarrollo humano', null, null, 16, 990, true, false),
  ('c-ingles-servicio', 'Inglés para Atención a Clientes y Call Center', 'El inglés que usas en el trabajo cuando atiendes a clientes extranjeros: contesta y cierra llamadas según guion, verifica datos y deletrea con el alfabeto fonético, calma a un cliente molesto, ofrece soluciones, vende sin presionar y atiende en hotel, restaurante, tienda, chat y correo. Incluye preparación para la entrevista y la evaluación de inglés de un call center. Para personas con nivel A2 o superior, con voz para escuchar cada frase y ejercicios de pronunciación.', '#0284C7', 'Cursos libres de capacitación', 'Idiomas', null, null, 16, 890, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
