-- Instituto Mara — tanda 8 del catálogo: idiomas (Inglés B2, Inglés para niños, Francés, Portugués, Italiano y Alemán A1).
-- Ejecutar en Supabase → SQL Editor ANTES de rutas.sql. Se puede repetir.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('c-ingles-b2', 'Inglés B2 (intermedio alto)', 'La continuación del Inglés B1, pensada para tu vida profesional: habla con matices (lo que habría pasado, lo que desearías, lo que prefieres), suaviza, persuade y negocia en juntas, presenta y cuenta historias con datos, maneja preguntas difíciles, escribe informes, propuestas y correos delicados (quejas, disculpas y rechazos) y gana fluidez natural con collocations, idioms y phrasal verbs de negocios. Con voz para escuchar cada frase y ejercicios de pronunciación. Curso libre de capacitación; no es una certificación oficial como Cambridge B2 First, TOEFL o IELTS.', '#3730A3', 'Cursos libres de capacitación', 'Idiomas', null, null, 28, 990, true, false),
  ('c-ingles-kids', 'Inglés para niños (con mamá o papá)', 'Un primer contacto con el inglés para niñas y niños de 6 a 10 años, pensado para estudiar en compañía de un adulto. En sesiones cortas de 10 a 15 minutos aprenden a saludar, decir su edad y cómo se sienten, los colores, los números del 1 al 20, las formas, la familia, la casa, los juguetes, los animales, la comida, el cuerpo y su rutina diaria. Escuchan cada palabra con voz, repiten, juegan con tarjetas, arman frases cortas, recitan rimas originales y hacen actividades lejos de la pantalla. Al final preparan un mini-show para la familia. El adulto no necesita saber inglés: la plataforma pronuncia todo. Nivel pre-A1 / A1 inicial del MCER.', '#F59E0B', 'Cursos libres de capacitación', 'Idiomas', null, null, 16, 790, true, false),
  ('c-frances-a1', 'Francés básico A1', 'Francés desde cero para hispanohablantes: saluda y preséntate, domina los sonidos que más cuestan (la r, la u, las nasales, las letras que no se pronuncian), da tus datos, habla de tu rutina y tus gustos, compra en la boulangerie y en el mercado, muévete por la ciudad, pide en un restaurante y cuenta lo que hiciste en tu viaje. Con voz para escuchar cada frase, ejercicios de pronunciación y alertas sobre los falsos amigos del español.', '#1D4ED8', 'Cursos libres de capacitación', 'Idiomas', null, null, 24, 890, true, false),
  ('c-portugues-a1', 'Portugués básico A1 (Brasil)', 'Portugués de Brasil desde cero para hispanohablantes: aprovecha todo lo que ya se parece al español y concéntrate en lo que cambia. Saluda y preséntate, domina los sonidos que delatan al principiante (las nasales de <i>ão</i>, la r que suena a j, el «chi» de <i>noite</i>), da tus datos, habla de tu rutina y tus gustos, compra en el súper y en la feira, muévete por la ciudad, pide en un restaurante y cuenta lo que hiciste en tu viaje a Río o São Paulo. Con voz para escuchar cada frase, ejercicios de pronunciación y alertas sobre los falsos amigos que más confunden.', '#059669', 'Cursos libres de capacitación', 'Idiomas', null, null, 24, 890, true, false),
  ('c-italiano-a1', 'Italiano básico A1', 'Italiano desde cero para hispanohablantes: aprovecha todo lo que se parece al español y entrena justo lo que cambia. Saluda y elige entre tu y Lei, domina los sonidos que engañan (ci, chi, gli, gn, sc y las dobles consonantes), da tus datos, habla de tu rutina y tus gustos, pide un café en el bar y compra en el mercado, muévete en tren y autobús, pide en un restaurante italiano respetando el orden de los platos y cuenta lo que hiciste en tu viaje. Con voz para escuchar cada frase, ejercicios de pronunciación y alertas sobre los falsos amigos del español.', '#DC2626', 'Cursos libres de capacitación', 'Idiomas', null, null, 24, 890, true, false),
  ('c-aleman-a1', 'Alemán básico A1', 'Alemán desde cero para hispanohablantes, paso a paso y sin asustarte: saluda, elige entre <i>du</i> y <i>Sie</i>, domina los sonidos que más cuestan (ä, ö, ü, ch, sch, ei, ie, w, z), da tus datos, aprende trucos para der, die y das, habla de tu rutina con los verbos separables, compra en la Bäckerei y en el súper, muévete en metro y tren, pide y paga en un restaurante y cuenta lo que hiciste en tu viaje a Berlín. Con voz para escuchar cada frase, ejercicios de pronunciación y alertas sobre los falsos amigos del español y del inglés.', '#374151', 'Cursos libres de capacitación', 'Idiomas', null, null, 28, 890, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;

-- Precio de la ruta de inglés (ahora incluye B2); rutas.sql no sobrescribe precios existentes
update cursos set precio = 2490 where id = 'r-ingles';
