-- Instituto Mara — diplomados nuevos (octubre 2026). Se puede repetir.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-seduccion-atraccion', 'Diplomado en Seducción: Psicología de la Atracción y Conexión', 'Aprende a atraer y conectar con honestidad, con base en la ciencia de las relaciones: primeras impresiones, presencia y cuidado personal, seguridad sin arrogancia, conversación y coqueteo respetuoso, autorrevelación, estilos de apego, apps de citas, primeras citas seguras, consentimiento, manejo del rechazo y el paso de conocer a alguien a una relación. Trabajarás con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para personas adultas de cualquier orientación sexual.', '#BE185D', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-imagen-personal', 'Diplomado en Imagen Personal y Estilo', 'Aprende a verte como quieres comunicar, sin reglas rígidas ni juicios sobre el cuerpo: colorimetría con telas y luz natural, proporciones, visagismo, códigos de vestimenta en México, armario cápsula, compras con presupuesto en pesos, cuidado de prendas, imagen en videollamadas y comunicación no verbal. Para personas de cualquier edad, cuerpo e identidad. Con casos mexicanos, 8 laboratorios, un proyecto final de asesoría completa y un cuaderno PDF.', '#B45309', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-psicologia-forense', 'Diplomado en Psicología Forense', 'Conoce cómo trabaja la psicología cuando sus conclusiones llegan a un juzgado: el sistema penal acusatorio mexicano, la pericial psicológica de principio a fin, la entrevista forense, los instrumentos y sus límites, la simulación, el testimonio y la memoria, el daño psíquico, la violencia familiar, la custodia, el riesgo de violencia, la prisión y la ética del perito. Trabajarás con casos ficticios mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para estudiantes y profesionales de la psicología, el derecho, el trabajo social y personas interesadas en el tema.', '#1E3A8A', 'Diplomados', 'Salud y bienestar', null, null, 30, 1690, true, false),
  ('d-lenguaje-corporal', 'Diplomado en Lenguaje Corporal y Comunicación No Verbal', 'Aprende a comunicar con el cuerpo lo que de verdad quieres decir y a interpretar las señales de los demás con prudencia. Recorrerás postura, gestos, rostro, mirada, voz, espacio personal, contacto, tiempo y apariencia; revisarás qué dice la evidencia sobre emociones y primeras impresiones, y desmontarás mitos populares. Practicarás grabándote en video para entrevistas, juntas, ventas, clases, videollamadas y la vida en familia, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#0F766E', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-psicologia-influencia', 'Diplomado en Psicología de la Influencia', 'Descubre qué dice la ciencia sobre cómo las personas influyen unas en otras en la vida diaria, el trabajo, las compras, la política y las redes. Estudiarás atajos mentales y sesgos, los principios de Cialdini con su evidencia y sus límites, cambio de actitudes, disonancia, conformidad, obediencia, influencia de minorías, normas sociales, nudges, algoritmos y desinformación. Aprenderás a detectar la influencia, a usarla con ética y a defenderte de su mal uso, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#7C3AED', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-leer-personas', 'Diplomado en Cómo Leer a las Personas', 'Aprende a comprender a las personas con precisión y empatía: qué piensan, qué sienten, qué necesitan y cómo deciden. Con lo que dice la investigación sobre precisión empática, sesgos al juzgar, personalidad (los Cinco Grandes), valores y emociones, practicarás un método claro: observar, formular hipótesis, preguntar y verificar, y ajustar. Lo aplicarás con clientes, jefes, equipos, pareja, hijos adolescentes y personas en crisis, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#0369A1', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-conversaciones-dificiles', 'Diplomado en Conversaciones Difíciles', 'Aprende a tener las conversaciones que sueles posponer: con tu jefe, tu equipo, tus clientes, tu familia y tu pareja. Con lo que proponen Stone, Patton y Heen, Rosenberg, Gottman y la investigación sobre emociones y retroalimentación, practicarás un método completo: prepararte, regularte, abrir sin atacar, escuchar, decir lo tuyo con claridad, dar malas noticias, poner límites, mediar y cerrar acuerdos que se cumplan. Con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#B91C1C', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-confianza-seguridad', 'Diplomado en Confianza y Seguridad Personal', 'Construye una confianza real, sin frases mágicas: con lo que dice la investigación sobre autoeficacia, autoestima realista, autocompasión, terapia cognitivo-conductual, síndrome del impostor, exposición gradual, asertividad, valores y hábitos. Aprenderás a callar al crítico interno, a enfrentar el miedo al rechazo paso a paso, a poner límites, a hablar en reuniones y entrevistas y a decidir con incertidumbre. Con casos mexicanos, 8 laboratorios, un proyecto final con tu plan de 30 días y un cuaderno PDF. Para cualquier persona adulta.', '#CA8A04', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-manipulacion', 'Diplomado en Psicología de la Manipulación: Cómo Detectarla y Protegerte', 'Aprende a distinguir la influencia legítima de la manipulación y a protegerte de ella. Con lo que dice la investigación sobre chantaje emocional, gaslighting, control coercitivo, acoso laboral, patrones oscuros, ingeniería social, grupos coercitivos y desinformación, practicarás un método para detectar señales, verificar, poner límites, documentar y pedir ayuda en México. Incluye casos de pareja, familia, trabajo, compras y fraudes, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#4C1D95', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-negociacion', 'Diplomado en Negociación y Poder de Influencia', 'Aprende a negociar con método y con números: salario y aumentos, compras y proveedores, clientes, renta, la venta de un auto y acuerdos en familia. Con el método de Harvard, la MAAN (BATNA), la zona de posible acuerdo, el anclaje, las concesiones, la escucha táctica y lo que dice la investigación sobre emociones, poder y sesgos, prepararás cada negociación con una plantilla, neutralizarás tácticas duras sin perder la ética y cerrarás acuerdos que se cumplen. Con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#0E7490', 'Diplomados', 'Negocios y finanzas', null, null, 30, 1690, true, false),
  ('d-storytelling', 'Diplomado en Storytelling: el arte de contar historias que conectan', 'Aprende a construir historias que se entienden, se recuerdan y mueven a actuar sin manipular. Trabajarás la estructura narrativa (Freytag, el viaje del héroe con sus críticas, la espina de la historia y el ABT de Randy Olson), personajes y detalle sensorial, lo que sí demuestra la investigación sobre transporte narrativo y lo que la neurociencia popular exagera. Luego lo aplicarás a tu historia personal, presentaciones, ventas éticas, liderazgo, datos y redes. Con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#C2410C', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-psicologia-social', 'Diplomado en Psicología Social para la Vida Real', 'Entiende por qué la gente hace lo que hace cuando hay otros alrededor: cómo se forma tu autoestima, por qué juzgamos rápido, cuándo cedemos ante el grupo o la autoridad, por qué nadie ayuda o casi todos ayudan, de dónde salen el prejuicio, la agresión y la polarización, y qué hacer con todo eso. Revisarás los experimentos clásicos con sus críticas actuales y lo que la crisis de replicación dejó en pie. Con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#15803D', 'Diplomados', 'Salud y bienestar', null, null, 30, 1690, true, false),
  ('d-detectar-mentiras', 'Diplomado en Cómo Detectar Mentiras: lo que dice la ciencia', 'Conoce a fondo el trabajo de Paul Ekman (emociones, microexpresiones, filtraciones, el error de Otelo) y contrástalo con lo que hoy muestra la investigación: por qué acertamos poco más que al azar, qué mitos conviene olvidar y qué sí funciona, como las preguntas inesperadas, los detalles verificables y el uso estratégico de la evidencia. Aplicarás todo a la pareja, el trabajo, las ventas, las entrevistas y los fraudes en línea, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#374151', 'Diplomados', 'Salud y bienestar', null, null, 30, 1690, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
