-- Instituto Mara — diplomados nuevos (octubre 2026). Se puede repetir.
insert into cursos (id, nombre, descripcion, color, nivel, familia, periodo_tipo, periodo_num, horas, precio, publicado, proximamente) values
  ('d-seduccion-atraccion', 'Diplomado en Seducción: Psicología de la Atracción y Conexión', 'Aprende a atraer y conectar con honestidad, con base en la ciencia de las relaciones: primeras impresiones, presencia y cuidado personal, seguridad sin arrogancia, conversación y coqueteo respetuoso, autorrevelación, estilos de apego, apps de citas, primeras citas seguras, consentimiento, manejo del rechazo y el paso de conocer a alguien a una relación. Trabajarás con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para personas adultas de cualquier orientación sexual.', '#BE185D', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-imagen-personal', 'Diplomado en Imagen Personal y Estilo', 'Aprende a verte como quieres comunicar, sin reglas rígidas ni juicios sobre el cuerpo: colorimetría con telas y luz natural, proporciones, visagismo, códigos de vestimenta en México, armario cápsula, compras con presupuesto en pesos, cuidado de prendas, imagen en videollamadas y comunicación no verbal. Para personas de cualquier edad, cuerpo e identidad. Con casos mexicanos, 8 laboratorios, un proyecto final de asesoría completa y un cuaderno PDF.', '#B45309', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-psicologia-forense', 'Diplomado en Psicología Forense', 'Conoce cómo trabaja la psicología cuando sus conclusiones llegan a un juzgado: el sistema penal acusatorio mexicano, la pericial psicológica de principio a fin, la entrevista forense, los instrumentos y sus límites, la simulación, el testimonio y la memoria, el daño psíquico, la violencia familiar, la custodia, el riesgo de violencia, la prisión y la ética del perito. Trabajarás con casos ficticios mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para estudiantes y profesionales de la psicología, el derecho, el trabajo social y personas interesadas en el tema.', '#1E3A8A', 'Diplomados', 'Salud y bienestar', null, null, 30, 1690, true, false),
  ('d-lenguaje-corporal', 'Diplomado en Lenguaje Corporal y Comunicación No Verbal', 'Aprende a comunicar con el cuerpo lo que de verdad quieres decir y a interpretar las señales de los demás con prudencia. Recorrerás postura, gestos, rostro, mirada, voz, espacio personal, contacto, tiempo y apariencia; revisarás qué dice la evidencia sobre emociones y primeras impresiones, y desmontarás mitos populares. Practicarás grabándote en video para entrevistas, juntas, ventas, clases, videollamadas y la vida en familia, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#0F766E', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-psicologia-influencia', 'Diplomado en Psicología de la Influencia', 'Descubre qué dice la ciencia sobre cómo las personas influyen unas en otras en la vida diaria, el trabajo, las compras, la política y las redes. Estudiarás atajos mentales y sesgos, los principios de Cialdini con su evidencia y sus límites, cambio de actitudes, disonancia, conformidad, obediencia, influencia de minorías, normas sociales, nudges, algoritmos y desinformación. Aprenderás a detectar la influencia, a usarla con ética y a defenderte de su mal uso, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#7C3AED', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false),
  ('d-leer-personas', 'Diplomado en Cómo Leer a las Personas', 'Aprende a comprender a las personas con precisión y empatía: qué piensan, qué sienten, qué necesitan y cómo deciden. Con lo que dice la investigación sobre precisión empática, sesgos al juzgar, personalidad (los Cinco Grandes), valores y emociones, practicarás un método claro: observar, formular hipótesis, preguntar y verificar, y ajustar. Lo aplicarás con clientes, jefes, equipos, pareja, hijos adolescentes y personas en crisis, con casos mexicanos, 8 laboratorios, un proyecto final y un cuaderno PDF. Para cualquier persona adulta.', '#0369A1', 'Diplomados', 'Desarrollo humano', null, null, 30, 1690, true, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, color = excluded.color,
  nivel = excluded.nivel, familia = excluded.familia, horas = excluded.horas, precio = excluded.precio,
  publicado = excluded.publicado, proximamente = excluded.proximamente;
